// Enemy tunables — speed, health, AI cadence, and per-enemy quirks.

export const ENEMY_SPIDER_SPEED = 80;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MIN = 500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_WAIT = 200;
export const ENEMY_SPIDER_HURT_PUSH_BACK_SPEED = 50;
export const ENEMY_SPIDER_MAX_HEALTH = 2;

export const ENEMY_WISP_SPEED = 50;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_X = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_Y = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_DURATION = 500;
export const ENEMY_WISP_MAX_HEALTH = 1;

export const ENEMY_BOSS_DROW_SPEED = 80;
export const ENEMY_BOSS_DROW_MAX_HEALTH = 6;
export const ENEMY_BOSS_DROW_DEATH_ANIMATION_DURATION = 3000;
export const ENEMY_BOSS_IDLE_STATE_DURATION = 3000;
export const ENEMY_BOSS_HIDDEN_STATE_DURATION = 1000;
export const ENEMY_BOSS_TELEPORT_STATE_INITIAL_DELAY = 150;
export const ENEMY_BOSS_TELEPORT_STATE_FINISHED_DELAY = 500;
export const ENEMY_BOSS_PREPARE_ATTACK_STATE_FINISHED_DELAY = 500;
export const ENEMY_BOSS_ATTACK_DAMAGE = 1;
export const ENEMY_BOSS_ATTACK_SPEED = 160;
export const ENEMY_BOSS_START_INITIAL_DELAY = 1000;
