export const SCENE_KEYS = {
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  UI_SCENE: 'UI_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
  RADIAL_MENU_SCENE: 'RADIAL_MENU_SCENE',
  LOBBY_SCENE: 'LOBBY_SCENE',
  LOADING_SCENE: 'LOADING_SCENE',
} as const;
