export const SCENE_KEYS = {
  SPLASH_SCENE: 'SPLASH_SCENE',
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  UI_SCENE: 'UI_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
  RADIAL_MENU_SCENE: 'RADIAL_MENU_SCENE',
  LOBBY_SCENE: 'LOBBY_SCENE',
  LOADING_SCENE: 'LOADING_SCENE',
  // --- New menu scenes ---
  MAIN_MENU_SCENE: 'MAIN_MENU_SCENE',
  CREATE_LOBBY_SCENE: 'CREATE_LOBBY_SCENE',
  JOIN_LOBBY_SCENE: 'JOIN_LOBBY_SCENE',
  ACCOUNT_SCENE: 'ACCOUNT_SCENE',
  OPTIONS_SCENE: 'OPTIONS_SCENE',
  CREDITS_SCENE: 'CREDITS_SCENE',
} as const;
