export const SCENE_KEYS = {
  PRELOAD_SCENE: 'PRELOAD_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  UI_SCENE: 'UI_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
  RADIAL_MENU_SCENE: 'RADIAL_MENU_SCENE',
  LOBBY_SCENE: 'LOBBY_SCENE',
  LOADING_SCENE: 'LOADING_SCENE',
  // Ported from UI branch (Phase 9.2):
  SPLASH_SCENE: 'SPLASH_SCENE',
  MAIN_MENU_SCENE: 'MAIN_MENU_SCENE',
  ACCOUNT_SCENE: 'ACCOUNT_SCENE',
  OPTIONS_SCENE: 'OPTIONS_SCENE',
  CREDITS_SCENE: 'CREDITS_SCENE',
} as const;
