import * as Phaser from 'phaser';
import { Element } from './types';

export const EVENT_BUS = new Phaser.Events.EventEmitter();

export const CUSTOM_EVENTS = {
  OPENED_CHEST: 'OPENED_CHEST',
  ENEMY_DESTROYED: 'ENEMY_DESTROYED',
  PLAYER_DEFEATED: 'PLAYER_DEFEATED',
  PLAYER_HEALTH_UPDATED: 'PLAYER_HEALTH_UPDATED',
  SHOW_DIALOG: 'SHOW_DIALOG',
  DIALOG_CLOSED: 'DIALOG_CLOSED',
  BOSS_DEFEATED: 'BOSS_DEFEATED',
  SPELL_CAST: 'SPELL_CAST',
  MANA_UPDATED: 'MANA_UPDATED',
  ELEMENT_CHANGED: 'ELEMENT_CHANGED',
  DEBUG_SPAWN_FLYING_OBELISK: 'DEBUG_SPAWN_FLYING_OBELISK',
  // Network events (Phase 1: LAN Foundation)
  NETWORK_PLAYER_UPDATE: 'NETWORK_PLAYER_UPDATE',
  NETWORK_SPELL_CAST: 'NETWORK_SPELL_CAST',
  NETWORK_BREATH_START: 'NETWORK_BREATH_START',
  NETWORK_BREATH_UPDATE: 'NETWORK_BREATH_UPDATE',
  NETWORK_BREATH_END: 'NETWORK_BREATH_END',
  NETWORK_EARTH_WALL_PILLAR: 'NETWORK_EARTH_WALL_PILLAR',
  NETWORK_EARTH_WALL_PILLAR_DESTROY: 'NETWORK_EARTH_WALL_PILLAR_DESTROY',
  NETWORK_ROOM_TRANSITION: 'NETWORK_ROOM_TRANSITION',
  NETWORK_PLAYER_DISCONNECTED: 'NETWORK_PLAYER_DISCONNECTED',
  NETWORK_PLAYER_RECONNECTED: 'NETWORK_PLAYER_RECONNECTED',
  NETWORK_LOBBY_UPDATED: 'NETWORK_LOBBY_UPDATED',
  NETWORK_LOBBY_STARTED: 'NETWORK_LOBBY_STARTED',
  NETWORK_CONNECTED: 'NETWORK_CONNECTED',
  NETWORK_DISCONNECTED: 'NETWORK_DISCONNECTED',
} as const;

export const PLAYER_HEALTH_UPDATE_TYPE = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
} as const;

export type PlayerHealthUpdateType = keyof typeof PLAYER_HEALTH_UPDATE_TYPE;

export type PlayerHealthUpdated = {
  currentHealth: number;
  previousHealth: number;
  type: PlayerHealthUpdateType;
};

export type ElementChangedData = {
  element: Element;
};