/**
 * Runtime-mutable copy of the static config constants.
 * Spells read values from here at cast-time so the debug panel can
 * change them live without reloading the page.
 */
import {
  FIRE_BOLT_SPEED,
  FIRE_BOLT_DAMAGE,
  FIRE_BOLT_COOLDOWN,
  FIRE_AREA_DAMAGE_PER_TICK,
  FIRE_AREA_COOLDOWN,
  EARTH_BOLT_SPEED,
  EARTH_BOLT_DAMAGE,
  EARTH_BOLT_COOLDOWN,
  EARTH_FIRE_EXPLOSION_DAMAGE,
  EARTH_FIRE_EXPLOSION_SCALE,
  EARTH_FIRE_EXPLOSION_BODY_RADIUS,
  EARTH_BUMP_DAMAGE,
  EARTH_BUMP_COOLDOWN,
  EARTH_BUMP_DURATION,
  EARTH_BUMP_KNOCKBACK_FORCE,
  EARTH_BUMP_KNOCKBACK_DURATION,
  LAVA_POOL_DAMAGE_PER_TICK,
  WATER_SPIKE_DAMAGE,
  WATER_SPIKE_COOLDOWN,
  WATER_TORNADO_DAMAGE_PER_TICK,
  WATER_TORNADO_COOLDOWN,
} from './config';

export const RUNTIME_CONFIG = {
  FIRE_BOLT_SPEED,
  FIRE_BOLT_DAMAGE,
  FIRE_BOLT_COOLDOWN,
  FIRE_AREA_DAMAGE_PER_TICK,
  FIRE_AREA_COOLDOWN,
  EARTH_BOLT_SPEED,
  EARTH_BOLT_DAMAGE,
  EARTH_BOLT_COOLDOWN,
  EARTH_FIRE_EXPLOSION_DAMAGE,
  EARTH_FIRE_EXPLOSION_SCALE,
  EARTH_FIRE_EXPLOSION_BODY_RADIUS,
  EARTH_BUMP_DAMAGE,
  EARTH_BUMP_COOLDOWN,
  EARTH_BUMP_DURATION,
  EARTH_BUMP_KNOCKBACK_FORCE,
  EARTH_BUMP_KNOCKBACK_DURATION,
  LAVA_POOL_DAMAGE_PER_TICK,
  WATER_SPIKE_DAMAGE,
  WATER_SPIKE_COOLDOWN,
  WATER_TORNADO_DAMAGE_PER_TICK,
  WATER_TORNADO_COOLDOWN,
};
